### PR TITLE
Update application.js

### PR DESCRIPTION
**Pull request by AnitaYCheng**
Switch use of `#` in headings to link icon like in the TTS handbook, to make the heading links accessible to screenreaders. This includes adding the SVG link icon to the application.

## Description of changes

> Describe what this pull request is changing. Try to use plain language as much
> as possible to help teammates understand what they are reviewing.

## Known issues

> If this pull request introduces anything that needs to be addressed later,
> note it here. Some examples might be if you introduced a new link that fails
> tests but will work when another pull request is merged; you created a new
> method placeholder but it does not yet have content; or your change breaks
> something else that will be removed later. If you create any issues to
> address issues created by this pull request, this is a good place to list
> them! You can delete this section if the PR does not introduce any new issues.

## Related issues

> If this pull request is associated with any other issues or pull requests,
> lis them here. If this PR *closes* an issue, list it as `closes #issue` so
> the issue will automatically be closed when the PR is merged. If there are no
> related issues or PRs, you can delete this section.

- 
- 

## Reviewers:

> In addition to assigning reviewers in the GitHub interface, please also list
> who you would like a review from here and, if applicable, what kind of review
> you would like from them. For example, you might ask one person to review
> content while someone else reviews visual layout.

- [ ] @username: please review content
- [ ]
- [ ]

### CODE REVIEW

**Comment by MelissaBraxton** [comment]
Hey Jason! 

Would you be up for reviewing this to see if it fixes the header issue? 

Two things: 
 - Anita ended up changing code in the application.js file because that seemed like the only way to go given how the site is structured. 
 - I can't seem to make the pages preview work to check it out (we're working w/ GH on the web rather than locally), so if you have any thoughts on why that's happening, we'd love to know! Or, if you run into problems with that, let us know!

**Comment by mgwalker** [comment]
@AnitaYCheng If you have access to create branches directly on this repo instead of using a fork, that will make cloud.gov Pages run the build. It doesn't build PRs from forks.

**Comment by MelissaBraxton** [comment]
Oh! I didn't pick up on this being a fork... Thanks @mgwalker!

**Comment by AnitaYCheng** [comment]
Duplicate PR, this was a separate branch before I was a member of the repo. #373 replaces this PR.

**Pull request closed without merging**
