### PR TITLE
Add a CI/CD step to check for broken links

### LINKED ISSUE #303: Add a CI/CD step to verify that all links to other parts of the guide are correct
The Jekyll version of the Handbook had a GitHub Action for this: https://github.com/18F/handbook/blob/last-jekyll/.github/workflows/lint_pr.yml#L29-L40

### PR DESCRIPTION
**Pull request by mgwalker**
This PR adds a two-step CI/CD test for broken or incorrect links within the UX Guide. It does not test external links.

It first checks links in the unbuilt source code looking for any internal links that do not begin with `{{ site.baseurl }}`. It does that using a `grep` expression that I don't understand but it worked for years for the Handbook and it found some issues in the UX Guide, so... I'm in favor of keeping it. 😜

Then it builds the site and checks links in the rendered HTML. It uses the html-proofer tool for that scan, and it checks that the page being linked to exists, and if the link is to a specific heading within the page, that the heading also exists.

---

The tests are currently failing due to some incorrect and broken links. Those are documented in #306.

This PR closes #303

### CODE REVIEW

**Review by echappen — CHANGES_REQUESTED** [review]
[blocking suggestion] It'd be good to have some documentation for future maintainers and content contributors on what this step does, and what to do if you find broken links. I can see a scenario where someone comes in to update content, and their pipeline fails because there's a broken link somewhere they didn't touch, and they think this prevents them from moving forward. Docs could be something simple like, "if you find broken links unrelated to your work, open a new issue and link to this original PR"

**Comment by mgwalker** [comment]
Added documentation to the wiki here: https://github.com/18F/ux-guide/wiki/Automated-testing

I'm going to play with getting the tests to add a comment to the PR linking to that wiki page if there are any failures to hopefully help with discoverability.

**Comment by mgwalker** [comment]
@echappen If you have time between new project onboarding, I believe this is ready to review again! There's documentation in place, and if the tests fail, the action will post a comment to the pull request directing folks to the documentation if they need it. Furthermore, I modified the `{{ site.baseurl }}` part of the test so that it creates file annotations to help quickly find the offender – it'll show up as a filename and line number on the actions page, but even cooler, it'll also show up in the `Files changed` tab of the PR.

**Review by echappen — APPROVED** [review]
Awesome-sauce. Thank you!

**Pull request merged**
