### PR TITLE
Refine Landing Page

### LINKED ISSUE #165: As a user, I want a landing page that clearly communicates what the UX guide is and how I can use it so that I know whether and how it will help me before I click further.
**Background**
Need to revise landing page in accordance with [guidance from the USWDS team](https://designsystem.digital.gov/page-templates/). 

**Acceptance criteria** 
- [ ] Landing page clearly explains what the guide is and how it can be used

**Tasks**
- [X] Mock new landing page and architecture
- [X] Review mocks with team
- [ ] Implement mocks

**Definition of done**
- [ ]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)

### PR DESCRIPTION
**Pull request by nickttng**
**Note:** This is a _draft_ PR. When the code is cleaned up, we will convert it to 'ready for review' PR before merging; however, we can begin discussion.

[Preview via Federalist](https://federalist-48b3228b-0241-4802-9442-e08ff5c3e680.app.cloud.gov/preview/18f/ux-guide/nng-refine-landing-page/)

**Why:** This PR addresses #165. 

**How:** (Description to come)

**Definition of Done:**
- [x] Close #165 
- [x] TBD by POs

### CODE REVIEW

**Comment by nickttng** [comment]
@MelissaBraxton and @qmanderson1 

Question: How do you decide which page should have a sub-nav in the sidenav? Length of content? If H2 has subheadings, i.e. H3-Hx? Amount of H2s? 

Does this question make sense?

**Comment by MelissaBraxton** [comment]
The Q does make sense! Length of content, primarily. The subsection nav is there to help folks navigate through the very lengthy "research" content. Are you seeing inconsistencies in the header styles? Or are there specific subsections you are thinking should be reflected in the side nav?

**Comment by nickttng** [comment]
@MelissaBraxton Cool, cool. This week, I'll scan through and create subnav for every H2

**Comment by nickttng** [comment]
@MelissaBraxton Also, Let's merge this PR and I'll start a new PR just for subnav task.

**Pull request merged**
