### PR TITLE
Update bias.md

### PR DESCRIPTION
**Pull request by bpdesigns**
## Description of changes
Overhaul of the Bias page based on the [doc](https://docs.google.com/document/d/1yY0TvT_7qfArXZBfjkWZygrhjXO-N1Vp3PVYj27nCao/edit#heading=h.pyopkektn91w) 

## Reviewers:
I'm looking for one or more eyes on this to make sure I've transferred the doc accurately. Minor edits and feedback are also welcome. TY!

### CODE REVIEW

**Comment by bpdesigns** [comment]
I'm unclear what is wrong with the internal links in the guide on this page.

**Comment by melchoyce** [comment]
Maybe since the bot doesn't have permission to access the internal pages, it thinks they don't exist?

**Comment by bpdesigns** [comment]
@mgwalker can you take a look at the internal link issue that is failing the automated check? See @melchoyce s comment above

**Comment by mgwalker** [comment]
I'll try to look at it in a little bit. Just looking at the changes, I don't see any reason for the link checks to be failing. It reads like the path `/research/bias/` doesn't exist, but it _should_. Could be a bug in the tests themselves.

**Comment by mgwalker** [comment]
New errors! Now it's about the in-page anchors. The previous error was due to some misplaced whitespace in the frontmatter of the biases page. One sec, I think I can fix this. 😂

**Comment by mgwalker** [comment]
Second batch of errors was due to case-mismatch. All of the headings get an auto-generated ID slug based on the content of the heading (e.g., '# What is bias?` gets an ID `what-is-bias`), but the slugs are always lowercase. Technically node IDs are case-sensitive, so using `#What-is-bias` will not match `#what-is-bias`.

**Comment by bpdesigns** [comment]
Thank you @mgwalker!

**Review by a-chappelear — APPROVED** [review]
Compared w/ doc - looks great!

**Pull request merged**
