### PR TITLE
Update participant-agreement.md

### PR DESCRIPTION
**Pull request by kmori**
Updating the language in the participant agreement to match our current Google Doc template language for research [with compensation](https://docs.google.com/document/d/18GLTggHUDI5MVrmL5Lbot58EB6c6tAkMbg54GqFaETc/edit) and [without compensation](https://docs.google.com/document/d/1EPElAVthOF2ojcoamRitDHSYK4lT9c5yFY8IBwbJNqE/edit#)

### CODE REVIEW

**Comment by kmori** [comment]
For more context on how/why these updates were made- @jstrothman & @kmori made edits to the participant agreement with the goals of:

- Increase plain language
- Reduce power imbalance of language in previous consent form
- Explain how information will be used
- Ask for consent on a more granular basis & explain opportunities to change your mind about consent
- Create a working document for more frequent iteration

We also went through a review process with OGC, Privacy, and the TTS Research Guild:

- 7/26/2022: OGC reviewed and approved updated language
- 7/26/2022: CPO confirmed it’s acceptable to link to the Privacy Act statement rather than include in full.
- 8/05/2022: Reviewed the new consent form with the Research Guild and made changes based on comments and feedback
- 9/20/2022: OGC provided guidance that the agreements would need to be signed with either a wet signature or GSA’s DSS (DocuSign)

These changes were initially made in our internal Google Docs and this pull request is to publish those changes in a publicly accessible setting.

**Comment by bpdesigns** [comment]
Looks good. Thank you @kmori and @jstrothman!

**Review by bpdesigns — COMMENTED** [review]
Looks good!

**Review by bpdesigns — COMMENTED** [review]
Looks good

**Pull request merged**
