### PR TITLE
Create a MVP footer

### PR DESCRIPTION
**Pull request by nickttng**
**Why:** Without a footer, does the site even exist? :the-thinker-statue:

[Preview via Federalist](https://federalist-48b3228b-0241-4802-9442-e08ff5c3e680.app.cloud.gov/preview/18f/ux-guide/nng-create-mvp-footer/)

**Note:** This PR is a MVP footer acting as its placeholder until we refine it further with Christine's recommendation in #158. 

**How:**
- Use USWDS-Jekyll's out-of-the-box configuration, but lightly customized, e.g. removed unnecessary elements (social icons, email, etc.) — See screenshot comparison below
- Add 'Return to top' anchor for quicker navigation

**When reviewing:** Is the proposal acceptable as a MVP? If not, what would be acceptable?

---

## Screenshot comparison

**Footer - Default / Out-of-the-box**
Footer with 18F logo, social icons and contact info

**Footer - Customized / Minimal** 
Footer with 18F logo only without social icons and contact info

### CODE REVIEW

**Comment by MelissaBraxton** [comment]
Thanks! I like the look of the new footer, but I'm not sure it meets the new (and evolving) brand guidance I've seen. I'm tagging in @cmajel who's been working w/ outreach on this. Do we need to include the GSA logo in the footer with the language about how ~this is a product of GSA/TTS maintained by 18F (a la [this example](https://camo.githubusercontent.com/f5c9bc0678e05eca08bb87c2fd8c9734eb057005/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563396537633465316133353565356362333236616533342f30383735386361342d626633632d343662372d396132342d373564633263303137656235))? Existing handbook footers are all over the map, and I'm unsure how much flexibility we're allowed to have going forward.  

@cmajel  can you weigh in here?

**Comment by cmajel** [comment]
@nickttng @MelissaBraxton I know this is an MVP, but I'd recommend including the GSA logo and the `[Site name] is a product of GSA’s Technology Transformation Services[Link to TTS], and managed by 18F[Link to 18F].` That gives us the GSA branding that we want, and also makes it clear who is managing the site and where they fit within GSA.

I've updated #158 with a link to the current demo if you want to pull from that code.

**Comment by nickttng** [comment]
@MelissaBraxton @cmajel Appreciate the feedback. I will merrily wander over to #158 to pull from the code (TY Christine) and keep on working on it.

**Comment by jstrothman** [comment]
I added me as a reviewer so I can confirm that we've got all the things mentioned in #179

**Comment by MelissaBraxton** [comment]
Will need some kind of footer including GSA logo and 18F logo at a min. prior to launch. Links can wait if need be. @nickttng, Dahianna suggested that you do something similar to what you helped with on the "join TTS" page. (cc @igorkorenfeld)

**Comment by nickttng** [comment]
Given the recent migration, I am closing this PR without merging. After adding `_includes` files, I will start afresh.

**Pull request closed without merging**
