### PR TITLE
Ik add search

### PR DESCRIPTION
**Pull request by igorkorenfeld**
This draft PR addresses #159 . I was able to add the site-handle to our config and the search box is now functional
👓 &nbsp;[Preview](https://federalist-48b3228b-0241-4802-9442-e08ff5c3e680.app.cloud.gov/preview/18f/ux-guide/ik-add-search/)

However, there are cases where it returns results to pages that are unstyled. For instance searching for "Interviews", the first three results have pages that have no or incorrect styling. 

I think this is because the permalink for those pages is just `/page-name` instead of their section name `/section/page-name`. So perhaps adding in the section name to the permalink may solve the issue. For instance changing the permalink for the `interview-checklist` to  `/resources/interview-checklist/` But I am not totally sure.

@nickttng thoughts?

### CODE REVIEW

**Comment by nickttng** [comment]
The bright blue square shows up when I was tabbing through to the search input, so this is a keyboard accessibility issue. We will need to remove it.

I can take a look, unless this is a quick effort for you.

tab-nav-secondary

**Comment by igorkorenfeld** [comment]
Ah yes, those secondary links. I can take a look at those next week. 
As far as search goes, do you think then I should change this to regular PR merge, and then treat the results pages as a separate issue?

**Comment by igorkorenfeld** [comment]
Update to hide the links so that tabbing doesn't focus on them.

**Comment by nickttng** [comment]
@igorkorenfeld LGTM. 

Re: results with unstyled pages, let's create a new issue

**Pull request merged**
